### ISSUE TITLE
Error when import jnerf

### ISSUE THREAD

**Issue by wangjialuu** [Jittor/JNeRF#17]
请问，当完成前述安装步骤，且import jittor正常，python3.7 -m jittor.test.test_example也正常，但import jnerf时，会出现以下报错：
请问这是什么原因，请问如何解决？
Ubuntu 18.04
CUDA Version 10.1.243
python 3.7.6

在python命令行中执行import jnerf后：

[i 0616 11:04:00.885104 04 cuda_flags.cc:32] CUDA enabled.
nvcc fatal   : Unknown option '-extended-lambda'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/projects/JNeRF/python/jnerf/__init__.py", line 2, in <module>
    from . import models
  File "/root/projects/JNeRF/python/jnerf/models/__init__.py", line 1, in <module>
    from . import networks
  File "/root/projects/JNeRF/python/jnerf/models/networks/__init__.py", line 1, in <module>
    from . import ngp_network
  File "/root/projects/JNeRF/python/jnerf/models/networks/ngp_network.py", line 7, in <module>
    from jnerf.ops.code_ops.fully_fused_mlp import FullyFusedMlp_weight
  File "/root/projects/JNeRF/python/jnerf/ops/code_ops/fully_fused_mlp.py", line 6, in <module>
    from jnerf.ops.code_ops.global_vars import global_headers, proj_options
  File "/root/projects/JNeRF/python/jnerf/ops/code_ops/global_vars.py", line 27, in <module>
    gv.sync()
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync)).

Types of your inputs are:
 self   = Var,
 args   = (),

The function declarations are:
 void sync(bool device_sync = false, bool weak_sync = true)

Failed reason:[f 0616 11:04:03.509241 04 parallel_compiler.cc:329] Error happend during compilation:
 [Error] source file location:/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70/jit/code__IN_SIZE_0__OUT_SIZE_1__out0_dim_1__out0_type_int32__HEADER___include__pcg32_h__names___hash_45159d6c03260bf1_op.cc
Compile operator(0/1)failed:Op(2:0:1:1:i0:o1:s0,code->3)

Reason: [f 0616 11:04:03.508791 04 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/usr/local/cuda/bin/nvcc" "/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70/jit/code__IN_SIZE_0__OUT_SIZE_1__out0_dim_1__out0_type_int32__HEADER___include__pcg32_h__names___hash_45159d6c03260bf1_op.cc"      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/root/.local/lib/python3.7/site-packages/jittor/src" -I/opt/conda/include/python3.7m -I/opt/conda/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/usr/local/cuda/include" -I"/root/.local/lib/python3.7/site-packages/jittor/extern/cuda/inc"  -lcudart -L"/usr/local/cuda/lib64" -Xlinker -rpath="/usr/local/cuda/lib64"  -I"/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70" -L"/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70" -Xlinker -rpath="/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70" -L"/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default" -Xlinker -rpath="/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default"  -l:"jit_utils_core.cpython-37m-x86_64-linux-gnu".so  -l:"jittor_core.cpython-37m-x86_64-linux-gnu".so  -x cu --cudart=shared -ccbin="/usr/bin/g++" --use_fast_math  -w  -I"/root/.local/lib/python3.7/site-packages/jittor/extern/cuda/inc"  -arch=compute_70  -code=sm_70   -I/root/projects/JNeRF/python/jnerf/ops/code_ops/../op_include/eigen -I/root/projects/JNeRF/python/jnerf/ops/code_ops/../op_include/include -I/root/projects/JNeRF/python/jnerf/ops/code_ops/../op_include/pcg32 -I/root/projects/JNeRF/python/jnerf/ops/code_ops/../op_include/../op_header -DGLOBAL_VAR --extended-lambda --expt-relaxed-constexpr   -o "/root/.cache/jittor/jt1.3.4/g++7.5.0/py3.7.6/Linux-3.10.0-1x5c/IntelRXeonRGolx80/default/cu10.1.243_sm_70/jit/code__IN_SIZE_0__OUT_SIZE_1__out0_dim_1__out0_type_int32__HEADER___include__pcg32_h__names___hash_45159d6c03260bf1_op.so"

**Comment by Gword** [comment]
您可以将`global_vars.py`里`-extended-lambda`换成`--expt-extended-lambda`再尝试import一下

**Comment by wangjialuu** [comment]
thx! It works.
