### ISSUE TITLE
Fail to generate valid test images and render valid video on lego dataset

### ISSUE THREAD

**Issue by BurtonQin** [Jittor/JNeRF#72]
Hardware: NVIDIA Tesla T4, cuda 11.3
JNeRF:
master branch
Description:
Test on lego dataset.
All the generated ./lego/test/lego_r_{number}.png is completely black.
TOTAL TEST PSNR is extremely low or even nan.
The rendered "demo.mp4" is completely black.

**Comment by BurtonQin** [comment]
Besides, `import jittor` and `import jnerf` seem OK and did not report any errors.

**Comment by ellzeycunha0** [comment]
I have the same issue, it is fixed by setting fp16 = False

**Comment by BurtonQin** [comment]
It worked! Thanks a lot! @ellzeycunha0
